name: Pytest

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 'latest'  # replace with your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt  # modify with your dependency installation command

      - name: Run pytest
        run: pytest manage_the_dungeon.py -v